/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mitogex;

import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.StackPane;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author mitogex
 */

public class Main_windows extends javax.swing.JFrame implements ComboBoxUpdater{

    /**
     * Creates new form main
     */
    public Main_windows() {
        initComponents();
        populateComboBoxWithDirectories();
        setLocationRelativeTo(null);
    }

    // Implement the updateComboBox method from the ComboBoxUpdater interface
    @Override
    public void updateComboBox() {
        populateComboBoxWithDirectories();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MitoGEx : Mitochondria Genome Explorer");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });

        jLabel1.setText("MultiQC");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("Fastp");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("FastQC Forward");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("FastQC Reverse");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setText("Variants");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setText("Haplogroup");

        jLabel7.setText("Alignment quality");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setText("Multi-Sample quality");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, 148, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1344, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("New...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Export HTML");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Exit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Execute");

        jMenuItem4.setText("Run all");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Quality Control");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Trimming");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Alignment");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Variant Calling");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Haplogroup ");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFrame new_proj = new new_proj(this);
        new_proj.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        new_proj.setVisible(true);
        new_proj.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Perform some action when the frame is closing
                int result = JOptionPane.showConfirmDialog(new_proj, "Are you sure you want to close this window?");
                if (result == JOptionPane.YES_OPTION) {
                    // Close the frame
//            new_proj.setVisible(false);
                    new_proj.dispose();
                }
            }
        });

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

//jEditorPane1.setContentType("text/html");
// File file = new File("/home/mitogex/FastQC/TMRC65015_1_fastqc.html");
//     jEditorPane1.setEditable(false);
//     try {
//       jEditorPane1.setPage(file.toURI().toURL());
//     }
//     catch (IOException e) {
//       
//       jEditorPane1.setText("<html>Could not load FastQC </html>");
//     } 
//JFrame frame1 = new JFrame("FastQC");
//        frame1.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        final JFXPanel fxPanel = new JFXPanel(){
//
//            @Override
//            public Dimension getPreferredSize() {
//                return new Dimension(1366, 768);
//            }
//        };
//        frame1.add(fxPanel, BorderLayout.CENTER);
//        frame1.pack();
//        frame1.setLocationRelativeTo(null);
//        frame1.setVisible(true);
        //**JLabel can't show
        jPanel3.add(new JLabel("<html><h3>Open FastQC output in new windows...</h3></html>"));
//jPanel3.repaint();
//getContentPane().add(jPanel3);
//setPreferredSize(new Dimension(1024, 600));
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        pack();
//        Platform.runLater(() -> {
//            initFX(fxPanel);
//        });

    }//GEN-LAST:event_jLabel1MouseClicked
    private void initFX(JFXPanel fxPanel) {
        // This method is invoked on the JavaFX thread
        Scene scene = createScene();
        fxPanel.setScene(scene);
    }

    private Scene createScene() {
        File f = new File("/home/mitogex/FastQC/TMRC65015_1_fastqc.html");
        StackPane root = new StackPane();
        Scene scene = new Scene(root);
        ScrollPane sp = new ScrollPane();
        sp.setContent(root);
        sp.setPannable(true);
        WebView webView = new WebView();
        WebEngine webEngine = webView.getEngine();
        webEngine.load(f.toURI().toString());
        root.getChildren().add(webView);
        return scene;
    }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
//        jEditorPane1.setContentType("text/html");
// File file = new File("/home/mitogex/NetBeansProjects/MitoGEx/Qualimap_results_9_file/multisampleBamQcReport.html");
//     jEditorPane1.setEditable(false);
//     try {
//       jEditorPane1.setPage(file.toURI().toURL());
//
//     }
//     catch (IOException e) {
//       
//       jEditorPane1.setText("<html>Could not load QualiMap </html>");
//     } 
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
//        jEditorPane1.setContentType("text/html");
// File file = new File("/home/mitogex/FastQC/TMRC65015_2_fastqc.html");
//     jEditorPane1.setEditable(false);
//     try {
//       jEditorPane1.setPage(file.toURI().toURL());
//
//     }
//     catch (IOException e) {
//       
//       jEditorPane1.setText("<html>Could not load FastQC </html>");
//     } 
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Get the working directory and modify it
        String workingDir = System.getProperty("user.dir");
        String newWorkingDir = workingDir.replace("target", "");
        String pathProgram = newWorkingDir + "/Results/";
        String selectedSample = (String) jComboBox1.getSelectedItem();
        if (selectedSample != null && !selectedSample.equals("Select...")) {
            // Define the paths to check for each program
            String baseDir = pathProgram;

            File fastQCDir = new File(baseDir + "FastQC/" + selectedSample);
            jLabel3.setVisible(fastQCDir.exists());

            File fastQCDir2 = new File(baseDir + "FastQC/" + selectedSample);
            jLabel4.setVisible(fastQCDir2.exists());

            File fastpDir = new File(baseDir + "Fastp/" + selectedSample);
            jLabel2.setVisible(fastpDir.exists());

            File multiQCDir = new File(baseDir + "MultiQC/");
            jLabel1.setVisible(fastQCDir.exists());
            
            File variantsDir = new File(baseDir + "ANNOVAR/");
            jLabel5.setVisible(variantsDir.exists());

            File haplogroupDir = new File(baseDir + "Haplogroup/" + selectedSample);
            jLabel6.setVisible(haplogroupDir.exists());
            
            File qualimapDir = new File(baseDir + "AlignmentQuality/" + selectedSample);
            jLabel7.setVisible(qualimapDir.exists());
            
            File multiQualimapDir = new File(baseDir + "MultiSample_QC/");
            jLabel8.setVisible(multiQualimapDir.exists());

            // Display FastQC_1 HTML in jPanel3 if it exists
            if (fastQCDir.exists()) {
                File fastQCFile = new File(fastQCDir, selectedSample + "_1_fastqc.html");
                if (fastQCFile.exists()) {
                    displayHTMLInPanel(fastQCFile.toURI().toString());
                } else {
                    System.out.println("FastQC HTML file not found: " + fastQCFile.getPath());
                }
            }

            // Add MouseListener to jLabel1 to display FastQC_1
            jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (fastQCDir.exists()) {
                        File fastQCFile = new File(fastQCDir, selectedSample + "_1_fastqc.html");
                        if (fastQCFile.exists()) {
                            displayHTMLInPanel(fastQCFile.toURI().toString());
                        } else {
                            System.out.println("FastQC HTML file not found: " + fastQCFile.getPath());
                        }
                    }
                }
            });

            // Add MouseListener to jLabel3 to display FastQC_2
            jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (fastQCDir2.exists()) {
                        File fastQCFile2 = new File(fastQCDir2, selectedSample + "_2_fastqc.html");
                        if (fastQCFile2.exists()) {
                            displayHTMLInPanel(fastQCFile2.toURI().toString());
                        } else {
                            System.out.println("FastQC HTML file not found: " + fastQCFile2.getPath());
                        }
                    }
                }
            });

            // Add MouseListener to jLabel4 to display MultiQC
            jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (multiQCDir.exists()) {
                        File multiQCFile = new File(multiQCDir, "multiqc_report.html");
                        if (multiQCFile.exists()) {
                            displayHTMLInPanel(multiQCFile.toURI().toString());
                        } else {
                            System.out.println("multiQC HTML file not found: " + multiQCFile.getPath());
                        }
                    }
                }
            });
            
            // Add MouseListener to jLabel4 to display Fastp
            jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (fastpDir.exists()) {
                        File fastpFile = new File(fastpDir, selectedSample + ".html");
                        if (fastpFile.exists()) {
                            displayHTMLInPanel(fastpFile.toURI().toString());
                        } else {
                            System.out.println("Fastp HTML file not found: " + fastpFile.getPath());
                        }
                    }
                }
            });
            
            // Add MouseListener to jLabel7 to display Alignment Quality
            jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (qualimapDir.exists()) {
                        File qualimapFile = new File(qualimapDir, "qualimapReport.html");
                        if (qualimapFile.exists()) {
                            displayHTMLInPanel(qualimapFile.toURI().toString());
                        } else {
                            System.out.println("Alignment Quality file not found: " + qualimapFile.getPath());
                        }
                    }
                }
            });
            
            // Add MouseListener to jLabel7 to display Alignment Quality
            jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (multiQualimapDir.exists()) {
                        File multiQualimapFile = new File(multiQualimapDir, "multisampleBamQcReport.html");
                        if (multiQualimapFile.exists()) {
                            displayHTMLInPanel(multiQualimapFile.toURI().toString());
                        } else {
                            System.out.println("Multi-Sample Quality file not found: " + multiQualimapFile.getPath());
                        }
                    }
                }
            });
            
            // Add MouseListener to jLabel5 to display Variants
            jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (qualimapDir.exists()) {
                        File variantsFile = new File(variantsDir, "variants_"+selectedSample+".html");
                        if (variantsFile.exists()) {
                            displayHTMLInPanel(variantsFile.toURI().toString());
                        } else {
                            System.out.println("Variants file not found: " + variantsFile.getPath());
                        }
                    }
                }
            });
            
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange

    }//GEN-LAST:event_jComboBox1PropertyChange

    private JFXPanel currentFxPanel;
    
public void ensureJavaFXIsInitialized() {
    if (Platform.isFxApplicationThread()) {
        return; // JavaFX is already initialized
    }

    SwingUtilities.invokeLater(() -> {
        new JFXPanel(); // This will initialize the JavaFX platform if not already done
    });
}
    
    private void displayHTMLInPanel(String url) {
         ensureJavaFXIsInitialized();  // Ensure JavaFX is initialized

    try {
        System.out.println("Loading URL: " + url);  // Log the URL

        jPanel3.removeAll();  // Clear previous content

        if (currentFxPanel != null) {
            System.out.println("Disposing old FxPanel");
            currentFxPanel = null;
        }

        currentFxPanel = new JFXPanel();
        currentFxPanel.setPreferredSize(new Dimension(800, 600));

        jPanel3.setLayout(new BorderLayout());
        jPanel3.add(currentFxPanel, BorderLayout.CENTER);

        Platform.runLater(() -> {
            WebView webView = new WebView();
            WebEngine webEngine = webView.getEngine();

            webEngine.load(null);
            webEngine.load(url);

            Scene scene = new Scene(webView);
            currentFxPanel.setScene(scene);

            System.out.println("Loaded URL successfully.");
        });

        jPanel3.revalidate();
        jPanel3.repaint();

    } catch (Exception e) {
        e.printStackTrace();  // Print out any exceptions to the console
    }
    }

    private void populateComboBoxWithDirectories() {
        String workingDir = System.getProperty("user.dir");
        String newWorkingDir = workingDir.replace("target", "");
        String pathProgram = newWorkingDir + "/Results/";

        System.out.println("Working directory: " + workingDir);
        System.out.println("Path to program: " + pathProgram);

        String[] programs = {"FastQC", "Fastp", "Qualimap2", "MultiQC", "Variants", "Haplogroup"};
        Set<String> sampleNames = new HashSet<>(); // Using a Set to ensure uniqueness
        for (String program : programs) {
            String pathProgramTools = pathProgram + program + "/";
            File directory = new File(pathProgramTools);

            if (directory.isDirectory() && directory.exists()) {
                // Get the list of directories (sample names) inside each program's directory
                String[] directoryNames = directory.list((current, name) -> new File(current, name).isDirectory());
                if (directoryNames != null) {
                    for (String directoryName : directoryNames) {
                        if (!directoryName.equals("multiqc_data")) { // Filter out "multiqc_data"
                            sampleNames.add(directoryName);
                        }
                    }
                }
            } else {
//            System.out.println("Invalid directory: " + pathProgramTools);
            }
        }
        // Populate the JComboBox with unique sample names
        SwingUtilities.invokeLater(() -> {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Select...");
            for (String sampleName : sampleNames) {
                jComboBox1.addItem(sampleName);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
//SwingUtilities.invokeLater(new Main_windows()::initAndShowGUI);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_windows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
