/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mitogex;

import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.StackPane;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.SwingWorker;

/**
 *
 * @author mitogex
 */

public class Main_windows extends javax.swing.JFrame implements ComboBoxUpdater{

    private final JFXPanel fxPanel = new JFXPanel();   // one per application
private WebView  webView;                          // created on the FX thread
private WebEngine webEngine;
    private String pendingUrl = null;
    /**
     * Creates new form main
     */
    public Main_windows() {
        initComponents();
        initBrowser();
        populateComboBoxWithDirectories();
        setLocationRelativeTo(null);
    }

    // Call this once, e.g. in the constructor *after* initComponents()
private void initBrowser() {
     ensureJavaFXIsInitialized();

        // place JFXPanel once
        jPanel3.setLayout(new BorderLayout());
        jPanel3.add(fxPanel, BorderLayout.CENTER);

        // build scene on FX thread
        Platform.runLater(() -> {
            webView   = new WebView();
            webEngine = webView.getEngine();
            fxPanel.setScene(new Scene(webView));

            // flush any early pending page
            if (pendingUrl != null) {
                webEngine.load(pendingUrl);
                pendingUrl = null;
            }else {
            // Load the HTML content directly after initialization
            String filePath = "https://mitogex.com/welcome.html"; // Replace this with the actual HTML file path
            displayHTMLInPanel(filePath);
        }
        });
}
    
    // Implement the updateComboBox method from the ComboBoxUpdater interface
    @Override
    public void updateComboBox() {
        populateComboBoxWithDirectories();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MitoGEx : Mitochondria Genome Explorer");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });

        jLabel1.setText("MultiQC");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("Fastp");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("FastQC Forward");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("FastQC Reverse");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setText("Variants");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setText("Haplogroup");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setText("Alignment quality");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setText("Multi-Sample quality");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setText("Tree");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, 148, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1344, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("New...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Share online...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Exit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFrame new_proj = new new_proj(this);
        new_proj.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        new_proj.setVisible(true);
        new_proj.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Perform some action when the frame is closing
                int result = JOptionPane.showConfirmDialog(new_proj, "Are you sure you want to close this window?");
                if (result == JOptionPane.YES_OPTION) {
                    // Close the frame
//            new_proj.setVisible(false);
                    new_proj.dispose();
                }
            }
        });

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

//jEditorPane1.setContentType("text/html");
// File file = new File("/home/mitogex/FastQC/TMRC65015_1_fastqc.html");
//     jEditorPane1.setEditable(false);
//     try {
//       jEditorPane1.setPage(file.toURI().toURL());
//     }
//     catch (IOException e) {
//       
//       jEditorPane1.setText("<html>Could not load FastQC </html>");
//     } 
//JFrame frame1 = new JFrame("FastQC");
//        frame1.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        final JFXPanel fxPanel = new JFXPanel(){
//
//            @Override
//            public Dimension getPreferredSize() {
//                return new Dimension(1366, 768);
//            }
//        };
//        frame1.add(fxPanel, BorderLayout.CENTER);
//        frame1.pack();
//        frame1.setLocationRelativeTo(null);
//        frame1.setVisible(true);
        //**JLabel can't show
        jPanel3.add(new JLabel("<html><h3>Open FastQC output in new windows...</h3></html>"));
//jPanel3.repaint();
//getContentPane().add(jPanel3);
//setPreferredSize(new Dimension(1024, 600));
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        pack();
//        Platform.runLater(() -> {
//            initFX(fxPanel);
//        });

    }//GEN-LAST:event_jLabel1MouseClicked
    private void initFX(JFXPanel fxPanel) {
        // This method is invoked on the JavaFX thread
        Scene scene = createScene();
        fxPanel.setScene(scene);
    }

    private Scene createScene() {
        File f = new File("/home/mitogex/FastQC/TMRC65015_1_fastqc.html");
        StackPane root = new StackPane();
        Scene scene = new Scene(root);
        ScrollPane sp = new ScrollPane();
        sp.setContent(root);
        sp.setPannable(true);
        WebView webView = new WebView();
        WebEngine webEngine = webView.getEngine();
        webEngine.load(f.toURI().toString());
        root.getChildren().add(webView);
        return scene;
    }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
//        jEditorPane1.setContentType("text/html");
// File file = new File("/home/mitogex/NetBeansProjects/MitoGEx/Qualimap_results_9_file/multisampleBamQcReport.html");
//     jEditorPane1.setEditable(false);
//     try {
//       jEditorPane1.setPage(file.toURI().toURL());
//
//     }
//     catch (IOException e) {
//       
//       jEditorPane1.setText("<html>Could not load QualiMap </html>");
//     } 
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
//        jEditorPane1.setContentType("text/html");
// File file = new File("/home/mitogex/FastQC/TMRC65015_2_fastqc.html");
//     jEditorPane1.setEditable(false);
//     try {
//       jEditorPane1.setPage(file.toURI().toURL());
//
//     }
//     catch (IOException e) {
//       
//       jEditorPane1.setText("<html>Could not load FastQC </html>");
//     } 
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Get the working directory and modify it
        String workingDir = System.getProperty("user.dir");
        String newWorkingDir = workingDir.replace("target", "");
        String pathProgram = newWorkingDir + "/Results/";
        String selectedSample = (String) jComboBox1.getSelectedItem();
        if (selectedSample != null && !selectedSample.equals("Select...")) {
            // Define the paths to check for each program
            String baseDir = pathProgram;

            File fastQCDir = new File(baseDir + "FastQC/" + selectedSample);
            jLabel3.setVisible(fastQCDir.exists());

            File fastQCDir2 = new File(baseDir + "FastQC/" + selectedSample);
            jLabel4.setVisible(fastQCDir2.exists());

            File fastpDir = new File(baseDir + "Fastp/" + selectedSample);
            jLabel2.setVisible(fastpDir.exists());

            File multiQCDir = new File(baseDir + "MultiQC/");
            jLabel1.setVisible(multiQCDir.exists());
            
            File variantsDir = new File(baseDir + "Web/");
            jLabel5.setVisible(variantsDir.exists());

            File haplogroupDir = new File(baseDir + "Web/");
            jLabel6.setVisible(haplogroupDir.exists());
            
            File qualimapDir = new File(baseDir + "AlignmentQuality/" + selectedSample);
            jLabel7.setVisible(qualimapDir.exists());
            
            File multiQualimapDir = new File(baseDir + "MultiSample_QC/");
            jLabel8.setVisible(multiQualimapDir.exists());
            
            File treeDir = new File(baseDir + "Phylogenetic/");
            jLabel9.setVisible(treeDir.exists());

            // Display FastQC_1 HTML in jPanel3 if it exists
            if (fastQCDir.exists()) {
                File fastQCFile = new File(fastQCDir, selectedSample + "_1_fastqc.html");
                if (fastQCFile.exists()) {
                    displayHTMLInPanel(fastQCFile.toURI().toString());
                } else {
                    System.out.println("FastQC HTML file not found: " + fastQCFile.getPath());
                }
            }

            // Add MouseListener to jLabel1 to display FastQC_1
            jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (fastQCDir.exists()) {
                        File fastQCFile = new File(fastQCDir, selectedSample + "_1_fastqc.html");
                       
                        if (fastQCFile.exists()) {
                           displayHTMLInPanel(toFixedFileURL(fastQCFile));

                        } else {
                            System.out.println("FastQC HTML file not found: " + fastQCFile.getPath());
                        }
                    }
                }
            });

            // Add MouseListener to jLabel3 to display FastQC_2
            jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (fastQCDir2.exists()) {
                        File fastQCFile2 = new File(fastQCDir2, selectedSample + "_2_fastqc.html");
                        if (fastQCFile2.exists()) {
                            displayHTMLInPanel(toFixedFileURL(fastQCFile2));
                        } else {
                            System.out.println("FastQC HTML file not found: " + fastQCFile2.getPath());
                        }
                    }
                }
            });

            // Add MouseListener to jLabel4 to display MultiQC
            jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (multiQCDir.exists()) {
                        File multiQCFile = new File(multiQCDir, "multiqc_report.html");
                        if (multiQCFile.exists()) {
                            displayHTMLInPanel(toFixedFileURL(multiQCFile));
                        } else {
                            System.out.println("multiQC HTML file not found: " + multiQCFile.getPath());
                        }
                    }
                }
            });
            
            // Add MouseListener to jLabel4 to display Fastp
            jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (fastpDir.exists()) {
                        File fastpFile = new File(fastpDir, selectedSample + ".html");
                        if (fastpFile.exists()) {
                            displayHTMLInPanel(toFixedFileURL(fastpFile));

                        } else {
                            System.out.println("Fastp HTML file not found: " + fastpFile.getPath());
                        }
                    }
                }
            });
            
            // Add MouseListener to jLabel7 to display Alignment Quality
            jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (qualimapDir.exists()) {
                        File qualimapFile = new File(qualimapDir, "qualimapReport.html");
                        if (qualimapFile.exists()) {
                            displayHTMLInPanel(toFixedFileURL(qualimapFile));
                        } else {
                            System.out.println("Alignment Quality file not found: " + qualimapFile.getPath());
                        }
                    }
                }
            });
            
            // Add MouseListener to jLabel7 to display Alignment Quality
            jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (multiQualimapDir.exists()) {
                        File multiQualimapFile = new File(multiQualimapDir, "multisampleBamQcReport.html");
                        if (multiQualimapFile.exists()) {
                           displayHTMLInPanel(toFixedFileURL(multiQualimapFile));
                        } else {
                            System.out.println("Multi-Sample Quality file not found: " + multiQualimapFile.getPath());
                        }
                    }
                }
            });
            
            // Add MouseListener to jLabel5 to display Variants
            jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (variantsDir.exists()) {
                        File variantsFile = new File(variantsDir, "variants_"+selectedSample+".html");
                        if (variantsFile.exists()) {
                            displayHTMLInPanel(toFixedFileURL(variantsFile));
                        } else {
                            System.out.println("Variants file not found: " + variantsFile.getPath());
                        }
                    }
                }
            });
            
            // Add MouseListener to jLabel5 to display Variants
            jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (haplogroupDir.exists()) {
                        File haplogroupFile = new File(haplogroupDir, "haplogroup.html");
                        if (haplogroupFile.exists()) {
                            displayHTMLInPanel(toFixedFileURL(haplogroupFile));
                        } else {
                            System.out.println("Haplogroup file not found: " + haplogroupFile.getPath());
                        }
                    }
                }
            });
            
            // Add MouseListener to jLabel5 to display Variants
            jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (treeDir.exists()) {
                        File treeFile = new File(treeDir, "tree.png");
                        if (treeFile.exists()) {
                            displayHTMLInPanel(toFixedFileURL(treeFile));
                        } else {
                            System.out.println("Tree file not found: " + treeFile.getPath());
                        }
                    }
                }
            });
            
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private String toFixedFileURL(File file) {
    return "file:///" + file.getAbsolutePath().replace("\\", "/");
}

    
    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange

    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    // Create uploading dialog
    final JDialog uploadingDialog = new JDialog((JFrame) null, "Uploading", false); // non-modal!
    uploadingDialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
    uploadingDialog.setSize(300, 100);
    uploadingDialog.setLocationRelativeTo(null);
    uploadingDialog.setLayout(new BorderLayout());
    uploadingDialog.add(new JLabel("📤 Uploading files to server...", SwingConstants.CENTER), BorderLayout.CENTER);

   

    SwingWorker<Void, Void> worker = new SwingWorker<>() {
        @Override
        protected Void doInBackground() {
            try {
                // Prompt for project name
                String projectTitle = JOptionPane.showInputDialog(null, "Enter your project name:");
                if (projectTitle == null || projectTitle.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Project name is required.", "Error", JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                projectTitle = projectTitle.trim().replaceAll("[^A-Za-z0-9_\\-]", "_");

                String workingDir = System.getProperty("user.dir");
                String new_workingDir = workingDir.replaceAll("target", "");
                String path_web = new_workingDir + "/Results/Web_online/";

                // Run bash script
                String scriptPath = new_workingDir + "/Software/scripts/Web/collect_web.sh";
                ProcessBuilder builder = new ProcessBuilder("/bin/bash", scriptPath, new_workingDir);
                builder.directory(new File(new_workingDir));
                builder.redirectErrorStream(true);
                // Show dialog (non-blocking)
    uploadingDialog.setVisible(true);
                Process process = builder.start();
                try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        System.out.println("[Script] " + line);
                    }
                }
                int exitCode = process.waitFor();
                if (exitCode != 0) {
                    throw new RuntimeException("❌ Pre-upload script failed with exit code: " + exitCode);
                }

                File htmlDir = new File(path_web);
                if (!htmlDir.exists()) {
                    throw new FileNotFoundException("Web directory not found.");
                }

                final String sessionId = Long.toHexString(System.currentTimeMillis());
                 final String finalProjectTitle = projectTitle;
                final Path baseDir = htmlDir.toPath();
                List<File> uploadedFiles = new ArrayList<>();
 
                Files.walk(baseDir)
                        .filter(Files::isRegularFile)
                        .filter(p -> {
                            String name = p.toString().toLowerCase();
                            return name.endsWith(".html") || name.endsWith(".htm") || name.endsWith(".txt") ||
                                    name.endsWith(".pdf") || name.endsWith(".css") || name.endsWith(".gif") ||
                                    name.endsWith(".png") || name.endsWith(".jpg") || name.endsWith(".jpeg") ||
                                    name.endsWith(".js");
                        })
                        .forEach(filePath -> {
                            try {
                                String relativePath = baseDir.relativize(filePath).toString().replace("\\", "/");
                                File htmlFile = filePath.toFile();
                                HTMLUploader.uploadReport(htmlFile, finalProjectTitle, sessionId, relativePath);
                                uploadedFiles.add(htmlFile);
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                        });

                if (uploadedFiles.size() < 5) {
                    // Show a message dialog to inform the user
    JOptionPane.showMessageDialog(null, 
        "Pipeline incomplete: The results may not be fully displayed due to fewer than 5 files being uploaded.", 
        "Incomplete Analysis", 
        JOptionPane.INFORMATION_MESSAGE);
                }

                // ✅ Delete local /Results/Web_online/ directory
                try {
                    Files.walk(baseDir)
                            .sorted(Comparator.reverseOrder())
                            .map(Path::toFile)
                            .forEach(File::delete);
                    System.out.println("✅ Cleaned up: " + baseDir);
                } catch (IOException cleanupEx) {
                    cleanupEx.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Warning: Failed to delete upload folder.", "Cleanup Warning", JOptionPane.WARNING_MESSAGE);
                }
                
                // ✅ Show final URL
                String folderUrl = "https://mitogex.com/shared/" + projectTitle + "_" + sessionId;
                JLabel label = new JLabel("<html>✅ Uploaded to: <a href='" + folderUrl + "'>" + folderUrl + "</a></html>");
                label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                label.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent e) {
                        try {
                            if (java.awt.Desktop.isDesktopSupported()) {
                                java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
                                if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                                    desktop.browse(new java.net.URI(folderUrl));
                                    return;
                                }
                            }
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                        copyToClipboard(folderUrl);
                        JOptionPane.showMessageDialog(null,
                                "✅ Your system doesn't support auto-opening the browser.\nLink copied to clipboard:\n" + folderUrl);
                    }
                });
                uploadingDialog.dispose();
                JButton copyButton = new JButton("📋 Copy Link");
                copyButton.addActionListener(e -> {
                    copyToClipboard(folderUrl);
                    JOptionPane.showMessageDialog(null, "Link copied to clipboard!");
                });

                JPanel panel = new JPanel(new BorderLayout());
                panel.add(label, BorderLayout.CENTER);
                panel.add(copyButton, BorderLayout.SOUTH);

                JOptionPane.showMessageDialog(null, panel, "Upload Successful", JOptionPane.INFORMATION_MESSAGE);
  
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Upload failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                // Always close loading dialog
                uploadingDialog.dispose();
            }
            return null;
        }
    };

    worker.execute(); // Start upload in background
    
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public static void copyToClipboard(String text) {
    java.awt.datatransfer.StringSelection selection = new java.awt.datatransfer.StringSelection(text);
    java.awt.Toolkit.getDefaultToolkit().getSystemClipboard().setContents(selection, null);
}

    
    private JFXPanel currentFxPanel;
    
public void ensureJavaFXIsInitialized() {
    try {
        Platform.startup(() -> {}); // Safe even if already started
    } catch (IllegalStateException ignored) {
        // JavaFX already initialized — ignore
    }
}
    
    private void displayHTMLInPanel(String url) {
         // Guarantee that the load happens on the JavaFX thread
    Platform.runLater(() -> {
        if (webEngine == null) {          // not ready yet
            pendingUrl = url;             // String field you create
            return;
        }
        webEngine.getLoadWorker().cancel();
        webEngine.load(url);
    });
    }

    private void populateComboBoxWithDirectories() {
        String workingDir = System.getProperty("user.dir");
        String newWorkingDir = workingDir.replace("target", "");
        String pathProgram = newWorkingDir + "/Results/";

        System.out.println("Working directory: " + workingDir);
        System.out.println("Path to program: " + pathProgram);

        String[] programs = {"FastQC", "Fastp", "Qualimap2", "MultiQC", "Variants", "Haplogroup"};
        Set<String> sampleNames = new HashSet<>(); // Using a Set to ensure uniqueness
        for (String program : programs) {
            String pathProgramTools = pathProgram + program + "/";
            File directory = new File(pathProgramTools);

            if (directory.isDirectory() && directory.exists()) {
                // Get the list of directories (sample names) inside each program's directory
                String[] directoryNames = directory.list((current, name) -> new File(current, name).isDirectory());
                if (directoryNames != null) {
                    for (String directoryName : directoryNames) {
                        if (!directoryName.equalsIgnoreCase("multiqc_data") && 
    !directoryName.equalsIgnoreCase("trees") &&
    !directoryName.equalsIgnoreCase("temp") &&
    !directoryName.equalsIgnoreCase("summary")) {
    sampleNames.add(directoryName);
}
                    }
                }
            } else {
//            System.out.println("Invalid directory: " + pathProgramTools);
            }
        }
        // Populate the JComboBox with unique sample names
        SwingUtilities.invokeLater(() -> {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Select...");
            for (String sampleName : sampleNames) {
                jComboBox1.addItem(sampleName);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
//SwingUtilities.invokeLater(new Main_windows()::initAndShowGUI);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_windows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
